name: Build and test user-java
run-name: ${{ github.actor }} is building and testing usr-java
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 15-challenge-4-build-test
    #paths:
      #- apis/user-java/**

env:
  JAVA_WORKING_DIRECTORY: apis/user-java
  TEST_FAILURE_MESSAGE: |
    ### Unit Test failure
    <details>
    <summary>Workflow details</summary>

    Workflow name: ${{ github.workflow }}
    Action: ${{ github.event_name }}
    Job: ${{ github.job }}
    PR: #${{ github.event.number }}
    </details>

    Test details: [Run #${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
    Pusher: @${{ github.actor }}

jobs:
  build_tests:
    defaults:
      run:
        working-directory: apis/user-java
    name: build_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Run tests with Maven
        run: mvn test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step if one of the step failed
        with:
          name: junit tests            # Name of the check run which will be created
          working-directory: ${{env.JAVA_WORKING_DIRECTORY}}/target/surefire-reports/
          path: "*.xml"    # Path to test results
          reporter: java-junit        # Format of test results

      - name: Add comment to PR
        uses: actions/github-script@v6
        if: ${{ failure() && github.event_name == 'pull_request'}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ env.TEST_FAILURE_MESSAGE }}`
            })
