name: Build and test user-java
run-name: ${{ github.actor }} is building and testing usr-java
on:
  workflow_dispatch:
  #pull_request:
  push:
    branches:
      - 15-challenge-4-build-test
    #paths:
      #- apis/user-java/**

jobs:
  build_tests:
    defaults:
      run:
        working-directory: apis/user-java
    name: build_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn test

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: junit tests            # Name of the check run which will be created
          path: target/surefire-reports/*.xml    # Path to test results
          reporter: java-junit        # Format of test results