name: IaC Pull Request validate
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    paths:
      - iac/**
jobs:
  pr-check:
    defaults:
      run:
        working-directory: iac/terraform  
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      run: terraform fmt -check

    - name: Terraform init local
      run: terraform init -backend=false

    - name: Terraform validation
      run: terraform validate
