name: IaC Pull Request validate
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    paths:
      - iac/**
jobs:
  my-second-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
    - name: Terraform fmt
      id: fmt
      run: iac/terraform/terraform_check.sh
#  my-first-job:
#    runs-on: ubuntu-latest
#    steps:
#      - run: echo "Hello Team !"