name: IaC Pull Request validate
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    paths:
      - iac/**
jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check iac/terraform

    - name: Terraform init local
      id: init_local
      run: terraform init -backend=false

    - name: Terraform validation
      id: validation
      run: terraform validate
