name: IaC Pull Request validate
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  pull_request:
    paths:
      - iac/**
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello Team !"
  my-second-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check iac/terraform
      continue-on-error: false